### ISSUE TITLE
Crawl Example

### ISSUE THREAD

**Issue by ghost** [testomato/minicrawler#2]
@pracj3am
Hey, Thanks for putting this project on Github. It is very interesting and i am glad i found it.

I have tried the example provided in README.md and also minicrawler executable in order to check the program but it seems that only first page is fetched, then program exits. 

Is that example correct ? It does not extracts urls to crawl. 

Thanks

**Comment by pracj3am** [comment]
Hey Mike!

Why do you think that only the first page is fetched? Following code works as expected (I have tried it).

``` c
#include <stdio.h>
#include <minicrawler/minicrawler.h>

static void onfinish(mcrawler_url *url, void *arg) {
    printf("%d: Status: %d\n", url->index, url->status);
}

void main() {
    mcrawler_url url[2];
    mcrawler_url *urls[] = {&url[0], &url[1], NULL};
    mcrawler_settings settings;
    memset(&url[0], 0, sizeof(mcrawler_url));
    memset(&url[1], 0, sizeof(mcrawler_url));
    mcrawler_init_url(&url[0], "http://example.com");
    url[0].index = 0;
    mcrawler_init_url(&url[1], "http://example.com");
    url[1].index = 1;
    mcrawler_init_settings(&settings);
    mcrawler_go(urls, &settings, &onfinish, NULL);
}
```

**Comment by ghost** [comment]
Thank you for the answer @pracj3am .

I had a look at the source code and it seems that links are not extracted from fetched contents.
I have still one question, How can we add links dynamically to the crawler while its running ? ( maybe in callback given to mcrawler_go function )

**Comment by pracj3am** [comment]
I see what you mean now. Despite its name minicrawler does not extract links from fetched content, only downloads content from provided urls. So crawling a website you have to implement yourself.

I would do it like this

``` c
void onfinish(mcrawler_url *url, void *arg) {
   mcrawler_url ***urls = (mcrawler_url ***)arg;
   mcrawler_url **found_links;
   find_links_in_content(found_links, url->buf, url->bufp);
   add_found_links_to_urls(urls, found_links)
}

void main() {
...
   mcrawler_url **urls, ***next;
   mcrawler_url *start[] = {&start_url, NULL};
   urls = start;
   for (i = 0; i < depth; i++) {
      mcrawler_go(urls, &settings, &onfinish, next);
      urls = *next;
   }
}
```

**Comment by ghost** [comment]
Thank you @pracj3am . I very appreciate your help.
It is clearer now. 
What happens to resolved DNS addresses ? are they cached internally ? or is it only done per call to mcrawler_go ?

**Comment by pracj3am** [comment]
They are cached only between subsequent redirects. So if call `mcrawler_go` with `http://example.com/a` which redirects to `http://example.com/b` minicrawler will do a single DNS request, But if you call `mcrawler_go` with two URLs `http://example.com/a` and `http://example.com/b` it will do two (same) request. 

It is not ideal, but we use pdnsd (http://members.home.nl/p.a.rombouts/pdnsd/index.html) as local DNS cache, so there was no need to solve it.

**Comment by ghost** [comment]
@pracj3am Thank you for your help. PDNSD looks interesting, i'll have a look.
